; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
uport = COM11
uspeed = 921600
mport = ${common.uport}
mspeed = 115200

lib_deps = 
    ; ..some library..

[platformio]
default_envs = bluepill

[env:bluepill]
platform = ststm32
framework = arduino
board = bluepill_f103c8
upload_protocol = dfu
monitor_port = ${common.mport}
monitor_speed = ${common.mspeed}
monitor_dtr = 1
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC

[env:bluepill_stlink]
platform = ststm32
framework = arduino
board = bluepill_f103c8
debug_tool = stlink
upload_protocol = stlink
monitor_port = ${common.mport}
monitor_speed = ${common.mspeed}

[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
framework = arduino
upload_protocol = stlink
debug_tool = stlink
monitor_port = ${common.mport}
monitor_speed = ${common.mspeed}
