; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = bluepill_hid


[common]
uport = COM11
uspeed = 921600
mport = ${common.uport}
mspeed = 115200

lib_deps = 
    ; ..some library..

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON



[env:bluepill_hid]
platform = https://github.com/platformio/platform-ststm32.git
;platform = ststm32
framework = arduino
board = bluepill_f103c8
upload_protocol = hid
upload_speed = ${common.uspeed}
monitor_port = ${common.mport}
monitor_speed = ${common.mspeed}
build_flags = ${common.build_flags}
lib_deps = ${common.lib_deps}

[env:bluepill_stlink]
platform = ststm32
framework = arduino
board = bluepill_f103c8
debug_tool = stlink
upload_protocol = stlink
monitor_port = ${common.mport}
monitor_speed = ${common.mspeed}
build_flags = ${common.build_flags}
lib_deps = ${common.lib_deps}

[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
framework = arduino
upload_protocol = stlink
debug_tool = stlink
monitor_port = ${common.mport}
monitor_speed = ${common.mspeed}
build_flags = ${common.build_flags}
lib_deps = ${common.lib_deps}